### ISSUE TITLE
"The mcrypt extension is missing"

### ISSUE THREAD

**Issue by andreasnymark** [Ecwid/kirby-ecwid-online-store#1]
I get an "The mcrypt extension is missing"-error trying to connect to existing Ecwid store, via the Ecwid widget. I’m running PHP 7.1.7, and the mcrypt module seems to be deprecated as of PHP 7.1.0.

Are you planning on replacing mcrypt or do I need to have it installed? This will eventually be installed on a shared webhost. Not sure yet if I can choose PHP version or if it’s installed.

**Comment by makfruit** [comment]
Hi,

Thank you for the report. I am afraid we're not going to fix that in the plugin in near future, so I'd suggest you installing the extension on your server. Sorry for the troubles caused by this. 

Another solution here would be using Ecwid JS integration code to add online store to your site — you don't a plugin for that, so the mcrypt extension won't be needed either. More details: https://support.ecwid.com/hc/en-us/articles/207359989-Adding-your-store-to-the-website-manually

**Comment by andreasnymark** [comment]
Thanks for getting back to me. I’ll have a look at the JS integration instead.
